notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: duoHkCiUwWbda2lhciTHvMGuK8lvWMkPnYQ4aJ3VJM88sFBjXOJ8JuduWHyUbSZmcxoo2LtjUuv9r+qe2m58OLjrPpyL883+RuTNuRVFts5ei8MeINH6N0yFt3POoMkkUmA6AJNovNsJjdS8zyNBU0pn/pea/d31TEGURTr1HTfySYmi+Saitq8FYtiI/TmFq7N7k710shUKZ0KNXn3JannUdDYd4azWEpV36hV3cs3HHvv2FaZR74PN42mFI5Cu0MU3J3OxyuFwl4vQG2K0kOCK6HC9+fRCFVqyqoEEqHAzDvOybhZb5GnCEg/uqVGhREZUn/1kzVdIAS2s40ZdbLjaTB468joXbif5bNNtQIISZoYfVsWlRkj4jY6Z4YMBMFQokbdxQGOZjKZFb/Q72Qu48ag3+8QnCPJOie8LAvYfFqzxN85UWtFHBSyQ9ivcguMZqfPCavjcCIceYh3amOi7K7gc+oaCFAbJzdNp6GpbOWQh5S3ApoevcUFdiBKU1Kf98HNnJKZQ75Lh6c7eGC8CdkO4Ddu1BrUMC0LV/3WCkpAqt6uy/g/N0jwz5JCuLIi/PZeCdElgQPPRAIVExgKm/tYmCDlVlPdz4wBkXpFVk8UTnhrG5sZ4lLHkqjMnO3H+ygnmz/ujCYS1nQJWMYuddeec94zpP6p6T3tlHng=
stages:
- name: BUILD
  if: commit_message !~ /(skip[ _-]build)/
- name: TEST
  if: commit_message !~ /(skip[ _-]test)/

jobs:
  include:
  - stage: BUILD
    language: node_js
    node_js:
    - '16'
    services:
    - docker
    script:
    - bash .travis.build.sh
  - stage: TEST
    language: node_js
    node_js:
    - '16'
    script:
    - bash .travis.test.sh
